#! /bin/sh

sxhkd &
compton &
wal -i ~/Pictures/DhGgOp7.jpg &
#tint2 -c ~/.config/tint2/tint2rc &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV 
bspc desktop I --layout monocle

bspc config border_width         5
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a feh state=floating center=true
bspc rule -a "R Graphics" state=floating center=true

#make mouse resize control a thing
bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

